import { resolveAffiliateUrl } from "@/lib/affiliate";
import type {
  BrandMeta,
  CategoryMeta,
  DealProduct,
  SeoGuideLink,
  StoreMeta,
} from "@/types/deal";

/** Raw mock rows — `affiliateUrl` may be null; normalized via `mockDeals`. */
type MockDealRow = Omit<
  DealProduct,
  | "affiliateUrl"
  | "usesProductUrlFallback"
  | "featured"
  | "trending"
  | "aiPick"
  | "homepageRank"
  | "bestDealsRank"
  | "top10Rank"
  | "excludeFromHubs"
> & {
  affiliateUrl: string | null;
  featured?: boolean;
  trending?: boolean;
  aiPick?: boolean;
  homepageRank?: number | null;
  bestDealsRank?: number | null;
  top10Rank?: number | null;
  excludeFromHubs?: boolean;
};

const now = new Date().toISOString();

export const mockCategories: CategoryMeta[] = [
  {
    name: "Electronics",
    slug: "electronics",
    description: "Laptops, audio, smart home, and accessories with verified drops.",
    dealCount: 128,
  },
  {
    name: "Home & Kitchen",
    slug: "home-kitchen",
    description: "Cookware, organization, and small appliances on promotion.",
    dealCount: 94,
  },
  {
    name: "Fashion",
    slug: "fashion",
    description: "Footwear, outerwear, and everyday essentials from trusted brands.",
    dealCount: 76,
  },
  {
    name: "Health & Fitness",
    slug: "health-fitness",
    description: "Recovery tools, wearables, and nutrition staples.",
    dealCount: 52,
  },
  {
    name: "Outdoor",
    slug: "outdoor",
    description: "Camping, hiking, and weather-ready gear.",
    dealCount: 41,
  },
];

export const mockBrands: BrandMeta[] = [
  { name: "Sony", slug: "sony", dealCount: 18 },
  { name: "Apple", slug: "apple", dealCount: 22 },
  { name: "Dyson", slug: "dyson", dealCount: 9 },
  { name: "Nike", slug: "nike", dealCount: 31 },
  { name: "KitchenAid", slug: "kitchenaid", dealCount: 14 },
  { name: "Garmin", slug: "garmin", dealCount: 11 },
];

export const mockStores: StoreMeta[] = [
  { name: "Amazon", slug: "amazon", domain: "amazon.com", dealCount: 210 },
  { name: "Best Buy", slug: "best-buy", domain: "bestbuy.com", dealCount: 48 },
  { name: "Target", slug: "target", domain: "target.com", dealCount: 36 },
  { name: "Walmart", slug: "walmart", domain: "walmart.com", dealCount: 28 },
  { name: "Nike", slug: "nike-store", domain: "nike.com", dealCount: 31 },
  { name: "REI", slug: "rei", domain: "rei.com", dealCount: 19 },
];

function hist(base: number, days: number[]) {
  return days.map((d, i) => ({
    price: Math.round(base + i * 3 + (i % 2) * 2),
    capturedAt: new Date(Date.now() - d * 86400000).toISOString(),
  }));
}

const mockDealsRaw: MockDealRow[] = [
  {
    id: "mock-1",
    slug: "sony-wh-1000xm5-wireless-headphones",
    source: "AMAZON_PA_API",
    title: "Sony WH-1000XM5 Wireless Noise Canceling Headphones — Black",
    normalizedTitle: "Sony WH-1000XM5 Wireless Headphones",
    brand: "Sony",
    category: "Electronics",
    subcategory: "Audio",
    imageUrl:
      "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=600&h=600&fit=crop",
    productUrl: "https://www.amazon.com/dp/example",
    affiliateUrl: "https://www.amazon.com/dp/example?tag=flashdealai-20",
    currency: "USD",
    currentPrice: 278,
    originalPrice: 399.99,
    discountPercent: 31,
    aiScore: 92,
    aiSummary:
      "Flagship ANC with strong mic quality; typical street price hovers higher.",
    aiReasonToBuy:
      "Largest recent drop in 30 days; strong reviews for travel and hybrid work.",
    availability: "In stock",
    rating: 4.7,
    reviewCount: 12400,
    tags: ["headphones", "travel", "ANC"],
    published: true,
    featured: true,
    trending: true,
    aiPick: true,
    homepageRank: 1,
    seoTitle: "Sony WH-1000XM5 deal — lowest price this month",
    seoDescription: "Compare today’s Sony WH-1000XM5 discount with 30-day price history.",
    lastSeenAt: now,
    priceHistory: hist(310, [30, 21, 14, 7, 3, 1]),
  },
  {
    id: "mock-2",
    slug: "apple-airpods-pro-2-usb-c",
    source: "BRAND_OFFICIAL",
    title: "Apple AirPods Pro (2nd Gen) with MagSafe Charging (USB‑C)",
    normalizedTitle: "Apple AirPods Pro 2 (USB-C)",
    brand: "Apple",
    category: "Electronics",
    subcategory: "Audio",
    imageUrl:
      "https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=600&h=600&fit=crop",
    productUrl: "https://www.apple.com/airpods-pro/",
    affiliateUrl: "https://www.apple.com/shop/go/airpods_pro?aff=flashdealai",
    currency: "USD",
    currentPrice: 199,
    originalPrice: 249,
    discountPercent: 20,
    aiScore: 88,
    aiSummary: "USB-C case aligns with newer iPhones; adaptive audio is the headline feature.",
    aiReasonToBuy:
      "Price matches recent lows; good moment if you want official warranty channels.",
    availability: "In stock",
    rating: 4.8,
    reviewCount: 56000,
    tags: ["apple", "earbuds", "usb-c"],
    published: true,
    trending: true,
    homepageRank: 2,
    lastSeenAt: now,
    priceHistory: hist(220, [28, 20, 12, 5, 2]),
  },
  {
    id: "mock-3",
    slug: "dyson-v15-detect-cordless-vacuum",
    source: "SCRAPED_RETAILER",
    title: "Dyson V15 Detect Absolute Cordless Vacuum",
    normalizedTitle: "Dyson V15 Detect Vacuum",
    brand: "Dyson",
    category: "Home & Kitchen",
    subcategory: "Cleaning",
    imageUrl:
      "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=600&h=600&fit=crop",
    productUrl: "https://www.bestbuy.com/site/example",
    affiliateUrl: "https://www.bestbuy.com/site/example?ref=flashdealai",
    currency: "USD",
    currentPrice: 599.99,
    originalPrice: 749.99,
    discountPercent: 20,
    aiScore: 86,
    aiSummary: "Laser dust detection plus torque head; premium tier within Dyson lineup.",
    aiReasonToBuy:
      "Discount aligns with seasonal promos; check replacement parts availability in your area.",
    availability: "Limited",
    rating: 4.6,
    reviewCount: 4200,
    tags: ["vacuum", "pets", "cordless"],
    published: true,
    aiPick: true,
    homepageRank: 3,
    lastSeenAt: now,
    priceHistory: hist(680, [45, 30, 14, 7]),
  },
  {
    id: "mock-4",
    slug: "nike-pegasus-41-mens-running-shoe",
    source: "MANUAL",
    title: "Nike Pegasus 41 Men's Road Running Shoes",
    normalizedTitle: "Nike Pegasus 41",
    brand: "Nike",
    category: "Fashion",
    subcategory: "Footwear",
    imageUrl:
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop",
    productUrl: "https://www.nike.com/t/example",
    affiliateUrl: "https://www.nike.com/t/example?cid=flashdealai",
    currency: "USD",
    currentPrice: 97.97,
    originalPrice: 140,
    discountPercent: 30,
    aiScore: 84,
    aiSummary: "Daily trainer refresh with ReactX foam; strong for easy miles.",
    aiReasonToBuy:
      "Size-dependent clearance pattern; AI flags unusually low price vs. 60-day median.",
    availability: "In stock",
    rating: 4.5,
    reviewCount: 890,
    tags: ["running", "clearance", "men"],
    published: true,
    homepageRank: 4,
    lastSeenAt: now,
    priceHistory: hist(125, [60, 45, 30, 14, 7]),
  },
  {
    id: "mock-5",
    slug: "kitchenaid-artisan-5qt-stand-mixer",
    source: "CSV_IMPORT",
    title: "KitchenAid Artisan Series 5 Quart Tilt-Head Stand Mixer",
    normalizedTitle: "KitchenAid Artisan 5 Qt Mixer",
    brand: "KitchenAid",
    category: "Home & Kitchen",
    subcategory: "Appliances",
    imageUrl:
      "https://images.unsplash.com/photo-1594383690141-4c4e2e0c0e0e?w=600&h=600&fit=crop",
    productUrl: "https://www.target.com/p/example",
    affiliateUrl: "https://www.target.com/p/example?afid=flashdealai",
    currency: "USD",
    currentPrice: 349.99,
    originalPrice: 449.99,
    discountPercent: 22,
    aiScore: 81,
    aiSummary: "Iconic countertop workhorse; holiday promos often stack with red card offers.",
    aiReasonToBuy:
      "Historical lows cluster in Q4; current price is within 5% of best observed deal.",
    availability: "In stock",
    rating: 4.8,
    reviewCount: 15200,
    tags: ["baking", "mixer", "gift"],
    published: true,
    homepageRank: 5,
    lastSeenAt: now,
    priceHistory: hist(410, [90, 60, 30, 14]),
  },
  {
    id: "mock-6",
    slug: "garmin-forerunner-255-music",
    source: "AMAZON_PA_API",
    title: "Garmin Forerunner 255 Music GPS Running Watch",
    normalizedTitle: "Garmin Forerunner 255 Music",
    brand: "Garmin",
    category: "Health & Fitness",
    subcategory: "Wearables",
    imageUrl:
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop",
    productUrl: "https://www.amazon.com/dp/garmin255",
    affiliateUrl: "https://www.amazon.com/dp/garmin255?tag=flashdealai-20",
    currency: "USD",
    currentPrice: 299.99,
    originalPrice: 399.99,
    discountPercent: 25,
    aiScore: 90,
    aiSummary: "Training load focus with music onboard; popular for half marathon plans.",
    aiReasonToBuy:
      "AI score boosted by sustained discount duration and stable inventory signals.",
    availability: "In stock",
    rating: 4.7,
    reviewCount: 3100,
    tags: ["gps", "running", "music"],
    published: true,
    homepageRank: 6,
    lastSeenAt: now,
    priceHistory: hist(360, [40, 28, 14, 7, 3]),
  },
  {
    id: "mock-7",
    slug: "rei-co-op-trailmade-2-person-tent",
    source: "BRAND_OFFICIAL",
    title: "REI Co-op Trailmade 2 Tent",
    normalizedTitle: "REI Trailmade 2 Tent",
    brand: "REI",
    category: "Outdoor",
    subcategory: "Camping",
    imageUrl:
      "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&h=600&fit=crop",
    productUrl: "https://www.rei.com/product/example",
    affiliateUrl: "https://www.rei.com/product/example?cm_mmc=flashdealai",
    currency: "USD",
    currentPrice: 119,
    originalPrice: 169,
    discountPercent: 30,
    aiScore: 79,
    aiSummary: "Lightweight two-person shelter; good entry for weekend backpacking.",
    aiReasonToBuy:
      "Seasonal clearance pattern; verify footprint compatibility before checkout.",
    availability: "In stock",
    rating: 4.4,
    reviewCount: 612,
    tags: ["camping", "backpacking", "clearance"],
    published: true,
    lastSeenAt: now,
    priceHistory: hist(155, [50, 35, 20, 10]),
  },
  {
    id: "mock-8",
    slug: "our-place-always-pan-2-0",
    source: "SCRAPED_RETAILER",
    title: "Our Place Always Pan 2.0 — Nonstick Ceramic Cookware",
    normalizedTitle: "Our Place Always Pan 2.0",
    brand: "Our Place",
    category: "Home & Kitchen",
    subcategory: "Cookware",
    imageUrl:
      "https://images.unsplash.com/photo-1584990349677-5e0ee0a8e8b0?w=600&h=600&fit=crop",
    productUrl: "https://fromourplace.com/products/example",
    affiliateUrl: "https://fromourplace.com/products/example?rfsn=flashdealai",
    currency: "USD",
    currentPrice: 99,
    originalPrice: 145,
    discountPercent: 32,
    aiScore: 83,
    aiSummary: "Space-saving design; bundles sometimes beat single-SKU pricing.",
    aiReasonToBuy:
      "AI notes bundle eligibility — compare cart total before clicking through.",
    availability: "In stock",
    rating: 4.3,
    reviewCount: 2100,
    tags: ["cookware", "starter-kitchen"],
    published: true,
    lastSeenAt: now,
    priceHistory: hist(130, [25, 18, 10, 4]),
  },
  {
    id: "mock-9",
    slug: "logitech-mx-keys-s-keyboard",
    source: "AMAZON_PA_API",
    title: "Logitech MX Keys S Wireless Keyboard",
    normalizedTitle: "Logitech MX Keys S",
    brand: "Logitech",
    category: "Electronics",
    subcategory: "Peripherals",
    imageUrl:
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&h=600&fit=crop",
    productUrl: "https://www.amazon.com/dp/mxkeyss",
    affiliateUrl: "https://www.amazon.com/dp/mxkeyss?tag=flashdealai-20",
    currency: "USD",
    currentPrice: 89.99,
    originalPrice: 119.99,
    discountPercent: 25,
    aiScore: 87,
    aiSummary: "Low-profile keys with smart illumination; strong for multi-device setups.",
    aiReasonToBuy:
      "Price drop corroborated across two retailers; affiliate link routes to lowest verified offer.",
    availability: "In stock",
    rating: 4.6,
    reviewCount: 5400,
    tags: ["keyboard", "work-from-home"],
    published: true,
    lastSeenAt: now,
    priceHistory: hist(105, [20, 14, 7, 2]),
  },
  {
    id: "mock-11",
    slug: "samsung-990-pro-2tb-nvme-ssd",
    source: "AMAZON_PA_API",
    title: "Samsung 990 PRO 2TB PCIe 4.0 NVMe SSD — Heatsink Option",
    normalizedTitle: "Samsung 990 PRO 2TB SSD",
    brand: "Samsung",
    category: "Electronics",
    subcategory: "Storage",
    imageUrl:
      "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=600&h=600&fit=crop",
    productUrl: "https://www.amazon.com/dp/samsung990pro",
    affiliateUrl: "https://www.amazon.com/dp/samsung990pro?tag=flashdealai-20",
    currency: "USD",
    currentPrice: 129.99,
    originalPrice: 229.99,
    discountPercent: 43,
    aiScore: 94,
    aiSummary: "PCIe 4.0 flagship; strong for PS5 expansion or creative workstations.",
    aiReasonToBuy:
      "Rare sub-$140 on 2TB tier; check heatsink requirement for your board.",
    availability: "In stock",
    rating: 4.8,
    reviewCount: 8900,
    tags: ["ssd", "storage", "gaming"],
    published: true,
    lastSeenAt: now,
    priceHistory: hist(180, [14, 10, 7, 3, 1]),
  },
  {
    id: "mock-12",
    slug: "anker-737-gan-charger-120w",
    source: "AMAZON_PA_API",
    title: "Anker 737 GaNPrime 120W 3-Port USB-C Charger",
    normalizedTitle: "Anker 737 120W GaN Charger",
    brand: "Anker",
    category: "Electronics",
    subcategory: "Accessories",
    imageUrl:
      "https://images.unsplash.com/photo-1583863788434-e58a18b9d29f?w=600&h=600&fit=crop",
    productUrl: "https://www.amazon.com/dp/anker737",
    affiliateUrl: "https://www.amazon.com/dp/anker737?tag=flashdealai-20",
    currency: "USD",
    currentPrice: 69.99,
    originalPrice: 99.99,
    discountPercent: 30,
    aiScore: 86,
    aiSummary: "Compact GaN brick for laptop + phone; travel-friendly foldable prongs.",
    aiReasonToBuy: "Matches recent Lightning Deal lows; good for multi-device desks.",
    availability: "In stock",
    rating: 4.6,
    reviewCount: 4100,
    tags: ["charger", "usb-c", "travel"],
    published: true,
    lastSeenAt: now,
    priceHistory: hist(85, [21, 14, 7]),
  },
  {
    id: "mock-13",
    slug: "google-nest-learning-thermostat-3rd-gen",
    source: "SCRAPED_RETAILER",
    title: "Google Nest Learning Thermostat (3rd Gen)",
    normalizedTitle: "Nest Learning Thermostat",
    brand: "Google",
    category: "Electronics",
    subcategory: "Smart Home",
    imageUrl:
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=600&fit=crop",
    productUrl: "https://www.bestbuy.com/site/nest-learning-thermostat",
    affiliateUrl: "https://www.bestbuy.com/site/nest-learning-thermostat?ref=flashdealai",
    currency: "USD",
    currentPrice: 179,
    originalPrice: 249,
    discountPercent: 28,
    aiScore: 82,
    aiSummary: "Learns schedules; works with most 24V HVAC setups — verify wiring.",
    aiReasonToBuy: "Utility rebates sometimes stack; compare with local programs.",
    availability: "In stock",
    rating: 4.5,
    reviewCount: 12000,
    tags: ["smart-home", "hvac", "energy"],
    published: true,
    lastSeenAt: now,
    priceHistory: hist(220, [30, 20, 10]),
  },
  {
    id: "mock-14",
    slug: "levis-501-original-fit-jeans",
    source: "BRAND_OFFICIAL",
    title: "Levi's 501 Original Fit Men's Jeans",
    normalizedTitle: "Levi's 501 Original Fit",
    brand: "Levi's",
    category: "Fashion",
    subcategory: "Denim",
    imageUrl:
      "https://images.unsplash.com/photo-1541099649105-f69ad21fb324?w=600&h=600&fit=crop",
    productUrl: "https://www.levi.com/US/en_US/clothing/men/jeans/501",
    affiliateUrl: "https://www.levi.com/US/en_US/clothing/men/jeans/501?cid=flashdealai",
    currency: "USD",
    currentPrice: 54.99,
    originalPrice: 89.5,
    discountPercent: 39,
    aiScore: 80,
    aiSummary: "Classic straight leg; waist sizing varies — check size guide.",
    aiReasonToBuy: "Clearance wash rotation; unusually low for core 501 lineup.",
    availability: "In stock",
    rating: 4.4,
    reviewCount: 6200,
    tags: ["denim", "men", "classic"],
    published: true,
    lastSeenAt: now,
    priceHistory: hist(72, [45, 30, 14]),
  },
  {
    id: "mock-15",
    slug: "columbia-powder-lite-jacket-mens",
    source: "SCRAPED_RETAILER",
    title: "Columbia Powder Lite Insulated Jacket — Men's",
    normalizedTitle: "Columbia Powder Lite Jacket",
    brand: "Columbia",
    category: "Fashion",
    subcategory: "Outerwear",
    imageUrl:
      "https://images.unsplash.com/photo-1544022613-e87ca75a37a6?w=600&h=600&fit=crop",
    productUrl: "https://www.columbia.com/p/powder-lite-jacket",
    affiliateUrl: "https://www.columbia.com/p/powder-lite-jacket?aff=flashdealai",
    currency: "USD",
    currentPrice: 79.99,
    originalPrice: 160,
    discountPercent: 50,
    aiScore: 91,
    aiSummary: "Synthetic insulation; packable for travel and shoulder seasons.",
    aiReasonToBuy: "Half-off seasonal push — size/color availability moves fast.",
    availability: "Limited sizes",
    rating: 4.5,
    reviewCount: 2100,
    tags: ["jacket", "winter", "outdoor"],
    published: true,
    lastSeenAt: now,
    priceHistory: hist(130, [60, 40, 20]),
  },
  {
    id: "mock-16",
    slug: "stanley-quencher-40oz-tumbler",
    source: "MANUAL",
    title: "Stanley Quencher H2.0 FlowState 40oz Tumbler",
    normalizedTitle: "Stanley Quencher 40oz",
    brand: "Stanley",
    category: "Home & Kitchen",
    subcategory: "Drinkware",
    imageUrl:
      "https://images.unsplash.com/photo-1513553404607-988bf2703777?w=600&h=600&fit=crop",
    productUrl: "https://www.target.com/p/stanley-quencher-40oz",
    affiliateUrl: "https://www.target.com/p/stanley-quencher-40oz?afid=flashdealai",
    currency: "USD",
    currentPrice: 35,
    originalPrice: 45,
    discountPercent: 22,
    aiScore: 77,
    aiSummary: "Viral tumbler; color drops sell out quickly at MSRP.",
    aiReasonToBuy: "Small but real discount; RedCard holders may save more in cart.",
    availability: "In stock",
    rating: 4.7,
    reviewCount: 45000,
    tags: ["tumbler", "hydration", "gift"],
    published: true,
    lastSeenAt: now,
    priceHistory: hist(42, [10, 5, 2]),
  },
  {
    id: "mock-17",
    slug: "theragun-mini-massage-gun",
    source: "AMAZON_PA_API",
    title: "Theragun Mini Portable Massage Gun (2nd Gen)",
    normalizedTitle: "Theragun Mini",
    brand: "Therabody",
    category: "Health & Fitness",
    subcategory: "Recovery",
    imageUrl:
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&h=600&fit=crop",
    productUrl: "https://www.amazon.com/dp/theragunmini",
    affiliateUrl: "https://www.amazon.com/dp/theragunmini?tag=flashdealai-20",
    currency: "USD",
    currentPrice: 159,
    originalPrice: 199,
    discountPercent: 20,
    aiScore: 84,
    aiSummary: "Compact percussion for travel; quieter than full-size Theragun Pro.",
    aiReasonToBuy: "Matches typical promo bands; good if you want first-party warranty.",
    availability: "In stock",
    rating: 4.6,
    reviewCount: 7800,
    tags: ["recovery", "fitness", "travel"],
    published: true,
    lastSeenAt: now,
    priceHistory: hist(185, [25, 18, 9]),
  },
  {
    id: "mock-18",
    slug: "google-pixel-8-unlocked-128gb",
    source: "BRAND_OFFICIAL",
    title: "Google Pixel 8 Unlocked 128GB Smartphone",
    normalizedTitle: "Google Pixel 8 128GB",
    brand: "Google",
    category: "Electronics",
    subcategory: "Phones",
    imageUrl:
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&h=600&fit=crop",
    productUrl: "https://store.google.com/product/pixel_8",
    affiliateUrl: "https://store.google.com/product/pixel_8?play=flashdealai",
    currency: "USD",
    currentPrice: 499,
    originalPrice: 699,
    discountPercent: 29,
    aiScore: 89,
    aiSummary: "Tensor G3 with strong camera stack; long software support pledge.",
    aiReasonToBuy: "Carrier trade-ins may beat this — compare total cost of ownership.",
    availability: "In stock",
    rating: 4.6,
    reviewCount: 11000,
    tags: ["android", "pixel", "camera"],
    published: true,
    lastSeenAt: now,
    priceHistory: hist(620, [45, 30, 14, 7]),
  },
  {
    id: "mock-19",
    slug: "instant-pot-duo-7-in-1-6qt",
    source: "SCRAPED_RETAILER",
    title: "Instant Pot Duo 7-in-1 Electric Pressure Cooker 6 Qt",
    normalizedTitle: "Instant Pot Duo 6 Qt",
    brand: "Instant Pot",
    category: "Home & Kitchen",
    subcategory: "Small Appliances",
    imageUrl:
      "https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=600&h=600&fit=crop",
    productUrl: "https://www.walmart.com/ip/instant-pot-duo-6qt",
    affiliateUrl: "https://www.walmart.com/ip/instant-pot-duo-6qt?aff=flashdealai",
    currency: "USD",
    currentPrice: 69,
    originalPrice: 99.95,
    discountPercent: 31,
    aiScore: 83,
    aiSummary: "Multi-cooker staple; 6 qt fits most families without hogging counter space.",
    aiReasonToBuy: "Everyday low price territory; watch for bundle accessories in cart.",
    availability: "In stock",
    rating: 4.7,
    reviewCount: 92000,
    tags: ["kitchen", "pressure-cooker", "meal-prep"],
    published: true,
    lastSeenAt: now,
    priceHistory: hist(88, [40, 25, 12]),
  },
  {
    id: "mock-20",
    slug: "keurig-k-elite-coffee-maker",
    source: "MANUAL",
    title: "Keurig K-Elite Single Serve Coffee Maker",
    normalizedTitle: "Keurig K-Elite",
    brand: "Keurig",
    category: "Home & Kitchen",
    subcategory: "Coffee",
    imageUrl:
      "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=600&h=600&fit=crop",
    productUrl: "https://www.target.com/p/keurig-k-elite",
    affiliateUrl: "https://www.target.com/p/keurig-k-elite?afid=flashdealai",
    currency: "USD",
    currentPrice: 99.99,
    originalPrice: 169.99,
    discountPercent: 41,
    aiScore: 85,
    aiSummary: "Iced button + strong brew; pod ecosystem lock-in is the tradeoff.",
    aiReasonToBuy: "Strong percent-off vs. list; bundle K-Cups often on separate promos.",
    availability: "In stock",
    rating: 4.5,
    reviewCount: 28000,
    tags: ["coffee", "keurig", "kitchen"],
    published: true,
    lastSeenAt: now,
    priceHistory: hist(140, [35, 20, 10]),
  },
  {
    id: "mock-21",
    slug: "bose-quietcomfort-45-headphones",
    source: "SCRAPED_RETAILER",
    title: "Bose QuietComfort 45 Wireless Noise Cancelling Headphones",
    normalizedTitle: "Bose QC45",
    brand: "Bose",
    category: "Electronics",
    subcategory: "Audio",
    imageUrl:
      "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=600&h=600&fit=crop",
    productUrl: "https://www.bestbuy.com/site/bose-qc45",
    affiliateUrl: "https://www.bestbuy.com/site/bose-qc45?ref=flashdealai",
    currency: "USD",
    currentPrice: 199,
    originalPrice: 329,
    discountPercent: 40,
    aiScore: 90,
    aiSummary: "Comfort-first ANC; warmer sound signature vs. Sony flagships.",
    aiReasonToBuy: "Deep cut from MSRP; compare return policy if fit is uncertain.",
    availability: "In stock",
    rating: 4.6,
    reviewCount: 15000,
    tags: ["headphones", "bose", "travel"],
    published: true,
    lastSeenAt: now,
    priceHistory: hist(280, [50, 35, 14, 7]),
  },
  {
    id: "mock-22",
    slug: "lego-icons-wildflower-bouquet",
    source: "AMAZON_PA_API",
    title: "LEGO Icons Wildflower Bouquet Building Set",
    normalizedTitle: "LEGO Wildflower Bouquet",
    brand: "LEGO",
    category: "Home & Kitchen",
    subcategory: "Gifts",
    imageUrl:
      "https://images.unsplash.com/photo-1582735689369-4fe89db7114c?w=600&h=600&fit=crop",
    productUrl: "https://www.amazon.com/dp/lego-wildflower",
    affiliateUrl: "https://www.amazon.com/dp/lego-wildflower?tag=flashdealai-20",
    currency: "USD",
    currentPrice: 39.99,
    originalPrice: 59.99,
    discountPercent: 33,
    aiScore: 78,
    aiSummary: "Display-friendly floral build; great gift when roses feel overplayed.",
    aiReasonToBuy: "Frequent small discounts; good filler to hit free shipping thresholds.",
    availability: "In stock",
    rating: 4.9,
    reviewCount: 22000,
    tags: ["lego", "gift", "decor"],
    published: true,
    lastSeenAt: now,
    priceHistory: hist(52, [18, 12, 6, 2]),
  },
  {
    id: "mock-10",
    slug: "draft-unpublished-example",
    source: "MANUAL",
    title: "Draft Product (Unpublished)",
    normalizedTitle: "Draft Product",
    brand: "Example",
    category: "Electronics",
    imageUrl: null,
    productUrl: "https://example.com",
    affiliateUrl: null,
    currency: "USD",
    currentPrice: 49,
    originalPrice: 99,
    discountPercent: 51,
    aiScore: 40,
    aiSummary: null,
    aiReasonToBuy: null,
    availability: "Unknown",
    rating: null,
    reviewCount: null,
    tags: [],
    published: false,
    lastSeenAt: now,
  },
];

function normalizeMockDeal(row: MockDealRow): DealProduct {
  return {
    ...row,
    featured: row.featured ?? false,
    trending: row.trending ?? false,
    aiPick: row.aiPick ?? false,
    homepageRank: row.homepageRank ?? null,
    bestDealsRank: row.bestDealsRank ?? null,
    top10Rank: row.top10Rank ?? null,
    excludeFromHubs: row.excludeFromHubs ?? false,
    affiliateUrl: resolveAffiliateUrl(row),
    usesProductUrlFallback: !row.affiliateUrl?.trim(),
  };
}

export const mockDeals: DealProduct[] = mockDealsRaw.map(normalizeMockDeal);

export const mockSeoGuides: SeoGuideLink[] = [
  {
    title: "How we verify lightning deals vs. list-price theater",
    href: "/about#methodology",
    blurb: "A practical breakdown of MSRP signals, coupon stacking, and real cart checks.",
  },
  {
    title: "Best time to buy electronics in the US",
    href: "/categories/electronics",
    blurb: "Seasonality, return windows, and when AI confidence scores peak.",
  },
  {
    title: "Affiliate disclosure & editorial independence",
    href: "/about#affiliate",
    blurb: "How FlashDealAI earns revenue without letting merchants buy placement.",
  },
];

export function getMockPublishedDeals(): DealProduct[] {
  return mockDeals.filter((d) => d.published);
}

export function getMockDealBySlug(slug: string): DealProduct | undefined {
  return mockDeals.find((d) => d.slug === slug && d.published);
}

export function getMockDealById(id: string): DealProduct | undefined {
  return mockDeals.find((d) => d.id === id && d.published);
}

export function getMockAllDealsForAdmin(): DealProduct[] {
  return mockDeals;
}
